{"uuid": "f3c24813-5c2f-4db4-bb70-6e8ce131aa85", "children": ["0f4a3992-856a-446d-a906-92c6d0e8c160"], "befores": [{"name": "page", "status": "passed", "start": 1715350275272, "stop": 1715350275329}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715350275332, "stop": 1715350275342}], "start": 1715350275272, "stop": 1715350275342}