{"uuid": "99cf0a24-5598-4fb4-96c9-2fa32387fb4f", "children": ["c1dbb09b-0ce2-45ef-a20e-5cb41b4861ef"], "befores": [{"name": "page", "status": "passed", "start": 1715350949071, "stop": 1715350949129}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715351013732, "stop": 1715351013743}], "start": 1715350949071, "stop": 1715351013743}