{"uuid": "83f8f996-1571-41c8-aed1-478ac436b6b2", "children": ["bf88d7cb-8140-4dd2-b96e-2a03feb05dd5"], "befores": [{"name": "page", "status": "passed", "start": 1715350884940, "stop": 1715350884997}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715350949045, "stop": 1715350949058}], "start": 1715350884940, "stop": 1715350949058}