{"uuid": "8fb0e828-bcdb-4b8a-8a3d-903276dccf31", "children": ["42655e7e-0952-4f85-8746-a52fca02da5c"], "befores": [{"name": "page", "status": "passed", "start": 1715350694400, "stop": 1715350694458}], "afters": [{"name": "page::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Dima\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dima\\Desktop\\Testing\\Python_Playwright\\ZegarowniaProject\\conftest.py\", line 30, in page\n    if request.node.rep_call and request.node.rep_call.failed:\n"}, "start": 1715350758002, "stop": 1715350758013}], "start": 1715350694400, "stop": 1715350758013}